const { BOOKING_STATUS } = require("../constants/bookingStatus");

const TRANSITIONS = {
  [BOOKING_STATUS.PENDING_PAYMENT]: [
    BOOKING_STATUS.PAID,
    BOOKING_STATUS.ACCEPTED,
    BOOKING_STATUS.ON_THE_WAY,
    BOOKING_STATUS.WORK_STARTED,
    BOOKING_STATUS.DELIVERED,
    BOOKING_STATUS.CANCELLED,
    BOOKING_STATUS.DISPUTED,
  ],

  // Backward compatibility for old bookings
  REQUESTED: [
    BOOKING_STATUS.PAID,
    BOOKING_STATUS.ACCEPTED,
    BOOKING_STATUS.ON_THE_WAY,
    BOOKING_STATUS.WORK_STARTED,
    BOOKING_STATUS.DELIVERED,
    BOOKING_STATUS.CANCELLED,
    BOOKING_STATUS.DISPUTED,
  ],

  [BOOKING_STATUS.PAID]: [
    BOOKING_STATUS.ACCEPTED,
    BOOKING_STATUS.ON_THE_WAY,
    BOOKING_STATUS.WORK_STARTED,
    BOOKING_STATUS.DELIVERED,
    BOOKING_STATUS.CANCELLED,
    BOOKING_STATUS.DISPUTED,
  ],

  [BOOKING_STATUS.ACCEPTED]: [
    BOOKING_STATUS.ON_THE_WAY,
    BOOKING_STATUS.WORK_STARTED,
    BOOKING_STATUS.DELIVERED,
    BOOKING_STATUS.CANCELLED,
    BOOKING_STATUS.DISPUTED,
  ],

  [BOOKING_STATUS.ON_THE_WAY]: [
    BOOKING_STATUS.WORK_STARTED,
    BOOKING_STATUS.DELIVERED,
    BOOKING_STATUS.CANCELLED,
    BOOKING_STATUS.DISPUTED,
  ],

  [BOOKING_STATUS.WORK_STARTED]: [
    BOOKING_STATUS.DELIVERED,
    BOOKING_STATUS.CANCELLED,
    BOOKING_STATUS.DISPUTED,
  ],

  [BOOKING_STATUS.DELIVERED]: [
    BOOKING_STATUS.COMPLETED,
    BOOKING_STATUS.DISPUTED,
    BOOKING_STATUS.CANCELLED,
  ],

  [BOOKING_STATUS.DISPUTED]: [
    BOOKING_STATUS.COMPLETED,
    BOOKING_STATUS.CANCELLED,
  ],

  [BOOKING_STATUS.COMPLETED]: [],
  [BOOKING_STATUS.CANCELLED]: [],
  [BOOKING_STATUS.REJECTED]: [],
};

const getAllowedTransitions = (currentStatus) => {
  return TRANSITIONS[currentStatus] || [];
};

const isValidTransition = (currentStatus, newStatus) => {
  if (currentStatus === newStatus) {
    return true;
  }

  return getAllowedTransitions(currentStatus).includes(newStatus);
};

module.exports = {
  getAllowedTransitions,
  isValidTransition,
};