const BOOKING_STATUS = Object.freeze({
  REQUESTED: "REQUESTED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  PAID: "PAID",
  ON_THE_WAY: "ON_THE_WAY",
  WORK_STARTED: "WORK_STARTED",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED",
  DISPUTED: "DISPUTED",
  CANCELLED: "CANCELLED",
});

module.exports = { BOOKING_STATUS };